# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-10 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title2',
        ),
    ]
